import sys
import os
import json
import urllib.request

def traverse(data, path):
    for key in path:
        data = data[key]
    return data

def send(context, prompt):
    request_body = json.loads(json.dumps(context["request_format"]))
    request_body["model"] = context["model"]
    request_body["messages"] = [{"role": "user", "content": prompt}]
    body_bytes = json.dumps(request_body).encode("utf-8")

    req = urllib.request.Request(
        context["endpoint"],
        data=body_bytes,
        headers={"Content-Type": "application/json"}
    )

    if context["auth_header"]:
        auth_value = context["key"]
        if context["auth_prefix"]:
            auth_value = context["auth_prefix"] + auth_value
        req.add_header(context["auth_header"], auth_value)

    if context.get("optional_headers"):
        for k, v in context["optional_headers"].items():
            req.add_header(k, v)

    with urllib.request.urlopen(req) as response:
        raw = response.read().decode("utf-8")
        response_json = json.loads(raw)

    text    = traverse(response_json, context["response_path"])
    in_tok  = traverse(response_json, context["input_token_path"])
    out_tok = traverse(response_json, context["output_token_path"])
    return text, in_tok, out_tok

def strip_backticks(text):
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1]
        text = text.rsplit("```", 1)[0].strip()
    return text

PROMPT_PREFIX = PROMPT_PREFIX = '''Refer to this as the TOC format and how a section is marked:

TABLE OF CONTENTS
=================
a1b2c3 = imports
d4e5f6 = config load
g7h8i9 = module variables

#a1b2c3-start
import os
import json
import getpass
import urllib.request
import time
from datetime import datetime
#a1b2c3-end

Help me generate a JSON array where each entry contains:
- hash: a unique 6-character alphanumeric key generated by you
- info: one concise sentence describing the section
- start: a single string containing the exact first three lines of the section joined by literal newline characters

Critical rules:
- start must be a plain string, not an array
- start must be a verbatim copy of the lines as they appear in the code
- Sections must be contiguous and exhaustive — every line in the file must belong to exactly one section with no lines left outside
- Decorators, inline directives, and annotations immediately preceding a definition belong to that definition's section, not the preceding one
- Return only valid JSON with no explanation, no markdown, no backticks
- Identify as many major sections as possible without clustering the code base

Example of correct start format:
"start": "import os\nimport json\nimport getpass"

Code:
'''

context = json.loads(sys.argv[1])
flag    = sys.argv[2] if len(sys.argv) > 2 else None
target  = sys.argv[3] if len(sys.argv) > 3 else None

if flag not in ("-json", "-verify", "-map", "-show") or target is None:
    print("!-Usage: do -agent codemap -json <source_file>|-verify <file-HASHTABLE.json> <source_file>|-map <source_file>|-show <file-HASHMAPPED> [hash]-!")
    sys.exit(1)

if not os.path.exists(target):
    print(f"!-File not found: {target}-!")
    sys.exit(1)

def hashtable_path(target):
    base    = os.path.splitext(os.path.basename(target))[0]
    out_dir = os.path.dirname(os.path.abspath(target))
    return os.path.join(out_dir, base + "-HASHTABLE.json")

def load_hashtable(target):
    path = hashtable_path(target)
    if not os.path.exists(path):
        print(f"!-Hashtable not found: {path}-!")
        sys.exit(1)
    try:
        with open(path, "r") as f:
            return json.load(f)
    except Exception as e:
        print(f"!-Failed to read hashtable: {e}-!")
        sys.exit(1)

def load_source(target):
    try:
        with open(target, "r") as f:
            return f.read()
    except Exception as e:
        print(f"!-Failed to read file: {e}-!")
        sys.exit(1)

def find_start_positions(lines, start_lines):
    matches = []
    for i in range(len(lines) - len(start_lines) + 1):
        if all(lines[i + j] == start_lines[j] for j in range(len(start_lines))):
            matches.append(i)
    return matches

def codemap_json(target):
    source = load_source(target)
    prompt = PROMPT_PREFIX + source
    text, in_tok, out_tok = send(context, prompt)
    text = strip_backticks(text)

    try:
        hashtable = json.loads(text)
    except json.JSONDecodeError as e:
        print(f"!-Invalid JSON from model: {e}-!")
        print(f"[debug] response: {text[:300]}")
        sys.exit(1)

    out_path = hashtable_path(target)
    try:
        with open(out_path, "w") as f:
            json.dump(hashtable, f, indent=2)
    except Exception as e:
        print(f"!-Failed to write HASHTABLE: {e}-!")
        sys.exit(1)

    print(f"[json] {out_path}")
    print(f"in:{in_tok} out:{out_tok}")

def resolve_starts(hashtable, lines):
    errors = []
    starts = []

    for entry in hashtable:
        start_lines = entry["start"].split("\n")
        matches     = find_start_positions(lines, start_lines)

        if len(matches) == 0:
            errors.append(f"!-[{entry['hash']}] start pattern not found-!")
        elif len(matches) > 1:
            errors.append(f"!-[{entry['hash']}] ambiguous: start pattern found at lines {[m+1 for m in matches]}-!")
        else:
            starts.append((matches[0], entry["hash"]))

    return sorted(starts, key=lambda x: x[0]), errors

def derive_end(starts, i, lines):
    if i + 1 < len(starts):
        next_start = starts[i + 1][0]
        if lines[next_start - 1] == "":
            return next_start - 2
        else:
            return next_start - 1
    else:
        return len(lines) - 1

def codemap_verify(hashtable_file, source_file):
    try:
        with open(hashtable_file, "r") as f:
            hashtable = json.load(f)
    except Exception as e:
        print(f"!-Failed to read hashtable: {e}-!")
        sys.exit(1)

    source         = load_source(source_file)
    lines          = source.splitlines()
    starts, errors = resolve_starts(hashtable, lines)

    if errors:
        for e in errors:
            print(e)
        sys.exit(1)

    for i, (start_pos, h) in enumerate(starts):
        end_pos = derive_end(starts, i, lines)
        print(f"[verify] {h} ok (lines {start_pos+1}-{end_pos+1})")

    print("[verify] all entries passed")

def codemap_map(target):
    hashtable      = load_hashtable(target)
    source         = load_source(target)
    lines          = source.splitlines()
    starts, errors = resolve_starts(hashtable, lines)

    if errors:
        for e in errors:
            print(e)
        sys.exit(1)

    insertions = []
    for i, (start_pos, h) in enumerate(starts):
        end_pos = derive_end(starts, i, lines)
        insertions.append((start_pos, end_pos, h))

    # pass 1: insert all #hash-start in reverse order
    for start_pos, end_pos, h in reversed(insertions):
        lines.insert(start_pos, f"#{h}-start")

    # pass 2: recalculate end positions accounting for start insertions, then insert ends + blank
    for start_pos, end_pos, h in reversed(insertions):
        shift   = sum(1 for sp, _, _ in insertions if sp <= end_pos)
        new_end = end_pos + shift
        lines.insert(new_end + 1, "")
        lines.insert(new_end + 1, f"#{h}-end")

    hash_to_info = {entry["hash"]: entry["info"] for entry in hashtable}
    toc_lines = ["# TABLE OF CONTENTS", "# ================="]
    for _, h in starts:
        toc_lines.append(f"# {h} = {hash_to_info[h]}")

    final_lines = toc_lines + [""] + lines
    instrumented = "\n".join(final_lines)

    ext      = os.path.splitext(target)[1]
    base     = os.path.splitext(os.path.basename(target))[0]
    out_dir  = os.path.dirname(os.path.abspath(target))
    out_path = os.path.join(out_dir, base + "-HASHMAPPED" + ext)

    try:
        with open(out_path, "w") as f:
            f.write(instrumented)
    except Exception as e:
        print(f"!-Failed to write HASHMAPPED file: {e}-!")
        sys.exit(1)

    print(f"[map] {out_path}")

def codemap_show(target, hash_key):
    if not os.path.exists(target):
        print(f"!-File not found: {target}-!")
        sys.exit(1)

    lines        = load_source(target).splitlines()
    start_marker = f"#{hash_key}-start"
    end_marker   = f"#{hash_key}-end"

    start_idx = None
    end_idx   = None

    for i, line in enumerate(lines):
        if line == start_marker:
            start_idx = i
        if line == end_marker:
            end_idx = i

    if start_idx is None:
        print(f"!-Section not found: {hash_key}-!")
        sys.exit(1)

    if end_idx is None:
        print(f"!-Malformed: start marker found but no end marker for {hash_key}-!")
        sys.exit(1)

    for line in lines[start_idx:end_idx + 1]:
        print(line)

if flag == "-json":
    print("---output---")
    codemap_json(target)
elif flag == "-verify":
    hashtable_file = sys.argv[3] if len(sys.argv) > 3 else None
    source_file    = sys.argv[4] if len(sys.argv) > 4 else None
    if hashtable_file is None or source_file is None:
        print("!-Usage: do -agent codemap -verify <hashtable_file> <source_file>-!")
        sys.exit(1)
    print("---output---")
    codemap_verify(hashtable_file, source_file)
elif flag == "-map":
    print("---output---")
    codemap_map(target)
elif flag == "-show":
    hash_key = sys.argv[4] if len(sys.argv) > 4 else None
    if hash_key is None:
        print("!--show requires a hash argument-!")
        sys.exit(1)
    print("---output---")
    codemap_show(target, hash_key)